CREATE SEQUENCE MY_SEQUENCE START WITH 1 INCREMENT BY 1;

BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO MyTable (id, val)
        VALUES (MY_SEQUENCE.NEXTVAL, FLOOR(DBMS_RANDOM.VALUE(1, 10000)));
    END LOOP;
    COMMIT;
END;
/

SELECT * FROM MYTABLE;